/** Retain the original Apple-style navigation, centered hero and product frame. */
import fs from 'node:fs';import path from 'node:path';import{fileURLToPath}from'node:url';
import{locales,ids,topics,topicNames}from'./home-copy.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),site=path.join(root,'website/public');
const m=JSON.parse(fs.readFileSync(path.join(root,'showcase/manifest.json'))),count=m.features.filter(f=>f.recording.status==='recorded').length;
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const hero={
 '':['Markdown stays yours.','A local-first Markdown reader and editor.','Pure Rust. Local first.','Read long documents. Edit with a live preview. Bring your files into Markdown, and export them beautifully.'],
 'zh-cn':['ReadMD 纯 Rust 原生版','本地优先的 Markdown 阅读器与编辑器','纯 Rust · 本地优先','长文档，轻松读。实时预览，安心写。将资料转为 Markdown，再以喜欢的方式导出。'],
 'zh-tw':['檔案留在本地。','本機優先的 Markdown 閱讀器與編輯器','純 Rust · 本機優先','長篇文件，輕鬆讀。即時預覽，安心寫。將資料轉為 Markdown，再以喜歡的方式匯出。'],
 'ja':['ファイルは手元に。','ローカル優先の Markdown リーダーとエディター','Pure Rust · ローカル優先','長い文書を快適に読む。プレビューを見ながら書く。資料を Markdown に変換し、好きな形式で書き出す。']};
for(const[prefix,c]of Object.entries(locales)){
 const file=path.join(site,prefix,'index.html'),old=fs.readFileSync(file,'utf8'),base=prefix?'/'+prefix+'/':'/';
 const faq=[];for(const match of old.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)){try{const data=JSON.parse(match[1]);for(const n of data['@graph']||[data])if(n['@type']==='FAQPage')faq.push(...n.mainEntity);}catch{}}
 let head=old.slice(0,old.indexOf('</head>')).replace(/<script[^>]*src="\/assets\/vendor\/[^\"]+"[^>]*><\/script>/g,'');
 head=head.replace(/<link rel="preload" as="image"[^>]+>/g,'<link rel="preload" as="image" href="/showcase/posters/F013.webp">');
 if(!head.includes('home.css'))head+='\n<link rel="stylesheet" href="/assets/home.css">';
 const cards=ids.map((id,i)=>`<a class="demo-card" href="/showcase/#${id}"><div class="demo-card-copy"><h3>${c.groups[i]}</h3><p>${c.descriptions[i]}</p><span class="link-action">${c.watch} <span aria-hidden="true">›</span></span></div><img src="/showcase/posters/${id}.webp" width="1280" height="800" loading="lazy" alt="${esc(c.groups[i])} · ReadMD"></a>`).join('');
 let[h1,sub,tag,intro]=hero[prefix];
 if(prefix==='zh-cn')h1='ReadMD <span class="home-title-phrase">纯 Rust 原生版</span>';
 const body=`<body class="antialiased readmd-home">
<a class="home-skip" href="#main">${c.guide}</a>
<header class="nav-shell sticky top-0 z-40"><div class="home-nav-inner mx-auto flex max-w-6xl items-center justify-between px-5"><a class="text-lg font-semibold tracking-tight" href="${base}">ReadMD</a><nav class="home-nav-links" aria-label="ReadMD"><a href="#capabilities">${c.guide}</a><a href="/showcase/">${c.watch}</a><a href="${base}download/#mcp-guide">MCP</a></nav><div class="home-nav-actions"><details class="home-languages"><summary aria-label="Language">文 / EN</summary><div><a href="/">English</a><a href="/zh-cn/">简体中文</a><a href="/zh-tw/">繁體中文</a><a href="/ja/">日本語</a></div></details><button id="home-theme" type="button" aria-label="Theme">◐</button><a class="button-primary" href="${base}download/">${c.download}</a></div></div></header>
<main id="main">
<section class="hero hero--poster mx-auto max-w-6xl px-5 pb-12 pt-16 text-center md:pt-24"><p class="home-eyebrow">${tag}</p><h1 class="hero-title mx-auto max-w-5xl">${h1}</h1><p class="home-subtitle">${sub}</p><p class="section-copy mx-auto mt-6 home-hero-copy">${intro}</p><div class="mt-8 flex flex-wrap justify-center gap-4"><a class="button-primary" href="${base}download/">${c.download}</a><a class="home-demo-link link-action" href="/showcase/">${c.watch} <span aria-hidden="true">›</span></a></div><figure class="product-frame mx-auto mt-14 max-w-5xl"><a href="/showcase/#F013" aria-label="${esc(c.watch+' · '+c.groups[0])}"><img src="/showcase/posters/F013.webp" width="1280" height="800" loading="eager" fetchpriority="high" decoding="async" alt="${esc(c.groups[0])} · ReadMD"></a></figure></section>
<section id="capabilities" class="home-demos"><div class="mx-auto max-w-6xl px-5"><div class="home-section-heading"><div><h2 class="display-title">${c.features}</h2></div><a class="link-action" href="/showcase/">${c.all} <span aria-hidden="true">›</span></a></div><div class="home-demo-grid">${cards}</div><p class="home-recording-note">${count} ${c.stats[0]} · 21 ${c.stats[2]}</p></div></section>
<section id="answers" class="py-20"><div class="mx-auto max-w-6xl px-5"><h2 class="display-title">${c.faq}</h2><div class="mt-12 grid gap-x-14 gap-y-10 md:grid-cols-2 xl:grid-cols-3">${faq.map(q=>`<article class="answer-card"><h3>${esc(q.name)}</h3><p>${esc(q.acceptedAnswer.text)}</p></article>`).join('')}<div class="col-span-full home-guide-links">${topics.map((slug,i)=>`<a class="link-action" href="${base}${slug}/">${topicNames[prefix][i]} <span aria-hidden="true">›</span></a>`).join('')}<a class="link-action" href="${base}workflows/">${c.guide} <span aria-hidden="true">›</span></a></div></div></div></section>
<section id="share" class="border-t border-[var(--color-line)] py-14"><div class="mx-auto max-w-4xl px-5 text-center"><h2 class="display-title">${c.share}</h2><div class="mt-6 flex flex-wrap justify-center gap-3"><a class="button-secondary" href="https://twitter.com/intent/tweet?url=https%3A%2F%2Frust.readmd.asia" rel="noopener">X</a><a class="button-secondary" href="https://t.me/share/url?url=https%3A%2F%2Frust.readmd.asia" rel="noopener">Telegram</a><a class="button-secondary" href="https://www.linkedin.com/sharing/share-offsite/?url=https%3A%2F%2Frust.readmd.asia" rel="noopener">LinkedIn</a></div></div></section>
</main><footer class="home-footer border-t border-[var(--color-line)] py-10 text-sm text-muted"><div class="mx-auto flex max-w-6xl flex-col gap-4 px-5 md:flex-row md:items-center md:justify-between"><p>© 2026 ReadMD · MIT</p><nav class="flex flex-wrap gap-5"><a href="${base}llms-full.txt">AI corpus</a><a href="${base}release-notes/">${topicNames[prefix][5]}</a><a href="https://github.com/Natsummerance/rust-ReadMD/stargazers">GitHub ★</a></nav></div></footer><script src="/assets/home.js" defer></script><script src="/assets/site.js" defer></script></body></html>`;
 fs.writeFileSync(file,head+'\n</head>\n'+body+'\n');
}console.log('Refined four home pages using the original Apple-style components');
