import fs from 'node:fs';
import path from 'node:path';
import {webFixture} from './web-fixture.mjs';
import {petRecipes} from './pet-recipes.mjs';
export const recipes = {};
Object.assign(recipes,petRecipes);
const add=(id,prepare,run,captureUi={})=>recipes[id]={prepare,run,captureUi};
const read=h=>h.open();
const edit=h=>h.edit();
const visible=async(h,selector)=>{await h.expect(h.page.locator(selector)).toBeVisible();h.evidence.push({assertion:'visible',selector});};
add('F001',null,async h=>{const chooser=h.page.waitForEvent('filechooser');await h.step('打开原创哲学阅读手册',()=>h.click('#w-open'));await (await chooser).setFiles(path.join(h.materials,'哲学阅读研究手册.md'));await h.expect(h.page.locator('#content h1').first()).toContainText('哲学阅读研究手册');h.evidence.push({assertion:'document_loaded_from_uploaded_file'});});
add('F003',null,async h=>{await h.step('新建文档并输入研究问题',()=>h.click('#w-new'));await h.text('# 阅读问题\n\n观察如何支持判断？');await h.assertText('观察如何支持判断');});
add('F004',null,async h=>{await h.step('快速开始：万物转 MD',()=>h.click('#w-convert'));await visible(h,'#convert-modal');await h.click('#convert-close');await h.step('快速开始：网页提取',()=>h.click('#w-web'));await visible(h,'#url-modal');});
add('F005',async h=>{await h.open();await h.page.evaluate(()=>goHome());},async h=>{await h.step('查看最近打开的资料',()=>h.click('#btn-recent'));await visible(h,'#history-modal');await h.step('清空最近记录',()=>h.click('#history-clear'));if(await h.page.locator('#confirm-action').isVisible())await h.click('#confirm-action');h.evidence.push({assertion:'recent_records_cleared',count:await h.page.evaluate(()=>state.recent?.length??null)});});
add('F006',read,async h=>{await h.step('返回主页，原文档保留在标签中',()=>h.click('#btn-home'));await h.expect.poll(()=>h.page.evaluate(()=>state.mode)).toBe('welcome');h.evidence.push({assertion:'welcome_mode'});});
add('F007',read,async h=>{await h.step('展开更多菜单并查看功能分组',()=>h.click('#btn-more'));await visible(h,'#more-menu');await h.click('.more-group-header');await h.step('打开命令面板',()=>h.click('#btn-palette'));await visible(h,'#command-palette-modal');});
add('F008',read,async h=>{const p=path.join(h.materials,'哲学阅读研究手册.md');fs.appendFileSync(p,'\n## 新增阅读记录\n\n检查刷新后的内容。\n');await h.step('刷新磁盘文件，显示新增记录',()=>h.click('#btn-reload'));await h.expect(h.page.locator('#content')).toContainText('检查刷新后的内容');h.evidence.push({assertion:'disk_change_loaded'});});
add('F009',async h=>{await h.open();await h.open('notes/认识与经验.md');await h.open('notes/自由与责任.md');},async h=>{await h.step('切换阅读标签',()=>h.click('.tab-item'));await h.step('关闭当前标签',()=>h.click('.tab-item.active .tab-close'));await h.expect.poll(()=>h.page.evaluate(()=>state.tabs.length)).toBe(2);h.evidence.push({assertion:'two_tabs_remain'});});
add('F010',async h=>{await h.open();await h.open('notes/认识与经验.md');},async h=>{await h.step('右键标签查看管理菜单',()=>h.page.locator('.tab-item').first().click({button:'right'}));await visible(h,'#tab-context-menu');await h.page.keyboard.press('Escape');const tabs=h.page.locator('.tab-item');await h.step('拖动标签调整顺序',()=>tabs.nth(0).dragTo(tabs.nth(1)));h.evidence.push({assertion:'tab_order',names:await h.page.evaluate(()=>state.tabs.map(t=>t.name))});});
add('F011',read,async h=>{await h.step('按 F2 重命名当前文档',()=>h.page.keyboard.press('F2'));const input=h.page.locator('.tab-title-input');await input.fill('哲学阅读修订稿');await input.press('Enter');await h.expect.poll(()=>h.page.evaluate(()=>getActiveTab().name)).toContain('哲学阅读修订稿');if(!fs.existsSync(path.join(h.materials,'哲学阅读修订稿.md')))throw Error('Rename did not write to disk');h.evidence.push({assertion:'renamed_file_exists'});});
add('F012',edit,async h=>{await h.text('\n\n保存前核对研究问题。');const d=h.page.waitForEvent('download');await h.step('另存为当前编辑内容',()=>h.more('btn-saveas'));const download=await d;const target=path.join(h.work,'saved.md');await download.saveAs(target);if(!fs.readFileSync(target,'utf8').includes('保存前核对研究问题'))throw Error('Downloaded stale document');h.evidence.push({assertion:'download_contains_current_draft'});});
add('F013',read,async h=>{await h.step('展开目录并定位章节',()=>h.click('#btn-toc'));await h.click('#toc-list a:last-child');await visible(h,'#toc-list');await h.step('收起侧栏',()=>h.click('#side-close-btn'));h.evidence.push({assertion:'outline_navigation'});});
add('F014',read,async h=>{await h.step('查找“观察”并切换匹配项',()=>h.click('#btn-search'));await h.page.locator('#search-input').fill('观察');await h.click('#search-next');await h.click('#search-prev');await h.expect(h.page.locator('#content mark').first()).toBeVisible();h.evidence.push({assertion:'search_matches',count:await h.page.locator('#content mark').count()});});
add('F016',null,async h=>{
 await h.expect(h.page.locator('#welcome')).toBeVisible();
 const themes=[];
 for(const [choice,label] of [['dark','深色'],['sepia','护眼'],['auto','自动'],['light','浅色']]){
  await h.step('在主页切换'+label+'主题',()=>h.click('#btn-theme'));
  await h.expect.poll(()=>h.page.evaluate(()=>state.theme)).toBe(choice);
  await h.expect(h.page.locator('#btn-theme')).toHaveAttribute('data-theme-icon',choice);
  await h.expect(h.page.locator('#welcome')).toBeVisible();
  const theme=await h.page.evaluate(async()=>{
   if(await settingsSaveQueue!==true)throw Error('Theme preference was not saved');
   return{choice:state.theme,resolved:document.body.dataset.theme,background:getComputedStyle(document.body).backgroundColor,saved:JSON.parse(localStorage.getItem('readmd-settings')).theme,system:matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'};
  });
  if(theme.saved!==choice||theme.resolved!==(choice==='auto'?theme.system:choice))throw Error('Home theme did not apply or persist');
  themes.push(theme);
 }
 if(themes[0].background===themes[3].background)throw Error('Home dark/light colors did not change');
 await h.step('打开阅读手册，调整字号',async()=>{await h.open();await h.click('#btn-A');});
 const larger=await h.page.evaluate(()=>state.fontSize);
 await h.click('#btn-a');
 if(await h.page.evaluate(()=>state.fontSize)>=larger)throw Error('Reader font controls did not change size');
 await h.step('进入禅模式，专注阅读',()=>h.click('#btn-zen'));
 await h.expect(h.page.locator('body')).toHaveClass(/zen-mode/);
 await h.page.keyboard.press('Escape');
 await h.expect(h.page.locator('body')).not.toHaveClass(/zen-mode/);
 h.evidence.push({assertion:'home_theme_cycle_applies_and_persists_with_reader_controls',themes,fontSizeRestored:true,zenExited:true});
},{hideToast:true,posterAt:1.2});
add('F017',read,async h=>{await h.step('打开阅读偏好，调整内容呈现',()=>h.click('#rd-prefs-btn'));await visible(h,'#rd-prefs');const range=h.page.locator('#rd-prefs input[type=range]').first();if(await range.count()){await range.fill('90');await range.dispatchEvent('input');await range.dispatchEvent('change');}h.evidence.push({assertion:'reader_preferences_open'});});
add('F018',async h=>h.open('notes/认识与经验.md'),async h=>{await h.step('点击双链，打开关联笔记',()=>h.click('#content a.wikilink'));await h.expect.poll(()=>h.page.evaluate(()=>state.file)).toContain('自由与责任.md');h.evidence.push({assertion:'linked_note_opened'});});
add('F019',read,async h=>{await h.step('复制代码块',()=>h.click('#content .rd-code-copy'));await h.step('点击插图放大查看',()=>h.click('#content img'));await visible(h,'#rd-lightbox-modal');await h.page.keyboard.press('Escape');h.evidence.push({assertion:'code_copy_and_image_lightbox'});});
add('F021',read,async h=>{await h.step('进入编辑，补充阅读结论',()=>h.click('#btn-edit'));await h.text('\n\n阅读结论：每个判断都需要检查前提。');await h.step('保存修改',()=>h.click('#edit-save'));await h.expect.poll(()=>fs.readFileSync(path.join(h.materials,'哲学阅读研究手册.md'),'utf8')).toContain('阅读结论');if(!await h.page.evaluate(()=>state.editing))await h.page.locator('#btn-edit').click();await h.text('\n这一句暂不采用。');await h.step('取消编辑，保留恢复记录',()=>h.click('#edit-cancel'));await h.click('#close-confirm-discard');h.evidence.push({assertion:'disk_saved_and_discard_keeps_source'});});
add('F022',edit,async h=>{await h.page.locator('.cm-content').click();await h.page.keyboard.press('Control+End');await h.step('使用工具栏插入加粗文字',()=>h.click('[data-md="bold"]'));await h.page.keyboard.insertText('研究结论');await h.click('[data-menu="md-structure-menu"]');await h.step('插入任务列表',()=>h.click('[data-md="task"]'));await h.assertText('研究结论');await h.assertText('[ ]');});
add('F023',edit,async h=>{await h.text('\n修订记录');await h.step('撤销刚才的输入',()=>h.click('#edit-undo'));await h.step('重做修改',()=>h.click('#edit-redo'));await h.click('#edit-view-trigger');await h.click('#edit-view-lines');await h.assertText('修订记录');});
add('F025',edit,async h=>{await h.page.locator('.cm-content').click();await h.page.keyboard.press('Control+End');await h.text('\n/');await h.step('斜杠菜单检索表格',()=>h.page.keyboard.type('table'));await h.page.keyboard.press('Enter');h.evidence.push({assertion:'slash_invoked',editor:await h.page.evaluate(()=>getEditContent().slice(-150))});});
add('F027',edit,async h=>{await h.step('切换为左右对照预览',()=>h.click('#pv-trigger'));await h.click('[data-pv="right"]');await visible(h,'#pv-pane');const r=await h.page.locator('#pv-splitter').boundingBox();await h.step('拖动分栏调整比例',async()=>{await h.page.mouse.move(r.x+r.width/2,r.y+80);await h.page.mouse.down();await h.page.mouse.move(r.x-100,r.y+80,{steps:10});await h.page.mouse.up();});h.evidence.push({assertion:'split_preview_resize'});});
add('F031',edit,async h=>{await h.step('插入表格并选择 3 × 3 网格',()=>h.insertMenu('btn-insert-table'));await h.click('.table-grid-cell[data-row="3"][data-col="3"]');await h.assertText('|');});
add('F032',edit,async h=>{await h.step('搜索并插入公式模板',()=>h.click('#formula-open'));await h.page.locator('#formula-search').fill('fraction');await h.click('.formula-item');await h.assertText('\\frac');});
add('F033',edit,async h=>{await h.step('插入可运行的 JavaScript 代码',()=>h.insertMenu('btn-insert-code-chunk'));await h.page.locator('#code-chunk-lang').selectOption('javascript');await h.page.locator('#code-chunk-code').fill('console.log(35 + 28 + 42 + 25);');await h.click('#code-chunk-insert');await h.assertText('35 + 28');});
add('F034',edit,async h=>{await h.step('插入论证关系图',()=>h.insertMenu('btn-insert-diagram'));await h.page.locator('#diagram-type').selectOption('mermaid');await h.page.locator('#diagram-code').fill('flowchart LR\n A[观察] --> B[前提]\n B --> C[结论]\n D[反例] --> B');await h.click('#diagram-insert');await h.assertText('flowchart LR');});
add('F035',edit,async h=>{await h.step('引用研究方法子文档',()=>h.insertMenu('btn-insert-doc-import'));await h.page.locator('#doc-import-path').fill('notes/研究方法.md');await h.click('#doc-import-insert');await h.assertText('研究方法.md');});
add('F036',edit,async h=>{await h.step('编辑文档标题和演示主题',()=>h.insertMenu('btn-insert-frontmatter'));await h.page.locator('#fm-input-title').fill('哲学阅读工作坊');await h.page.locator('#fm-input-author').fill('ReadMD 阅读小组');await h.page.locator('#fm-select-theme').selectOption('moon');await h.click('#fm-modal-insert');await h.assertText('哲学阅读工作坊');await h.assertText('moon');});
add('F096',read,async h=>{await h.step('打开命令面板，搜索阅读功能',()=>h.click('#btn-palette'));await h.page.locator('#cmdp-input').fill('目录');await visible(h,'#command-palette-modal');await h.page.keyboard.press('Enter');h.evidence.push({assertion:'command_search_and_execute'});});
add('F099',read,async h=>{await h.page.locator('#content h2').last().scrollIntoViewIfNeeded();await h.step('一键回到文档顶部',()=>h.click('#top-btn'));await h.expect.poll(()=>h.page.evaluate(()=>window.scrollY)).toBeLessThan(10);h.evidence.push({assertion:'scroll_top'});});
add('F102',edit,async h=>{await h.text('\n\n副本中尝试新的论证。');await h.step('创建编辑副本，保留原文件',()=>h.more('btn-document-copy'));await h.assertText('副本中尝试新的论证');await h.expect.poll(()=>h.page.evaluate(()=>state.file)).toBe(null);if(fs.readFileSync(path.join(h.materials,'哲学阅读研究手册.md'),'utf8').includes('副本中尝试'))throw Error('Copy changed original');h.evidence.push({assertion:'virtual_copy_original_untouched'});});
add('F103',edit,async h=>{await h.text('\n\n待核查的阅读结论');await h.page.evaluate(()=>ReadMDRecovery.flush());await h.step('查看恢复草稿',()=>h.more('btn-document-history'));await visible(h,'#document-history-modal');await h.step('将草稿作为副本打开',()=>h.page.locator('.document-history-row').filter({hasText:'哲学阅读研究手册'}).first().locator('button').first().click());await h.assertText('待核查的阅读结论');h.evidence.push({assertion:'recovery_copy_opened'});});

add('F015',async h=>{let s='# 哲学阅读档案\n\n';for(let i=1;i<=12;i++){s+=`## 第 ${i} 次阅读讨论\n\n`;for(let j=1;j<=750;j++)s+=`阅读记录 ${j}：描述观察，列出前提，检查结论。\n`;}fs.writeFileSync(path.join(h.materials,'长篇阅读档案.md'),s);await h.open('长篇阅读档案.md');},async h=>{await h.step('跳转下一页与末页',()=>h.click('#pg-next-btn'));await h.click('#pg-last-btn');await h.click('#pg-first-btn');await h.step('切换连续阅读',()=>h.click('#pg-mode-toggle'));if(await h.page.locator('#continuous-confirm').isVisible())await h.click('#continuous-confirm');h.evidence.push({assertion:'pagination',state:await h.page.evaluate(()=>({pages:state.pagination.pages.length,mode:state.pagination.mode}))});});
add('F020',async h=>{fs.appendFileSync(path.join(h.materials,'哲学阅读研究手册.md'),'\n## 参考文献\n\n演示书目 [@reading2026]。\n');await h.open();},async h=>{await h.step('查看正文文献引用与书目信息',async()=>{const citation=h.page.locator('.bib-citation,.citation,.cite-link').first();await citation.scrollIntoViewIfNeeded();await citation.hover();});await h.delay(550);h.evidence.push({assertion:'citation_rendered',text:await h.page.locator('#content').innerText()});});
add('F024',async h=>{await edit(h);await h.text('\n研究结论');await h.page.keyboard.press('Home');await h.page.keyboard.press('Shift+End');},async h=>{await h.step('选区工具条为文字加粗',()=>h.click('#cm-sel-bold'));await h.assertText('**研究结论**');});
add('F026',edit,async h=>{await h.page.evaluate(()=>navigator.clipboard.writeText('主题\t阅读分钟\n认识与经验\t35\n自由与责任\t28'));await h.page.locator('.cm-content').click();await h.page.keyboard.press('Control+End');await h.text('\n');await h.step('粘贴电子表格，自动转换为 Markdown 表格',()=>h.page.keyboard.press('Control+V'));await h.assertText('|');await h.assertText('认识与经验');});
const imagePrepare=async h=>{await edit(h);await h.page.locator('[data-menu="md-insert-menu"]').click();await h.page.locator('[data-md="image"]').filter({visible:true}).click();await h.page.locator('#img-file-input').setInputFiles(path.join(h.materials,'reading-map.png'));await h.expect.poll(()=>h.page.evaluate(()=>imgState.rawW)).toBeGreaterThan(0);};
add('F028',edit,async h=>{await h.step('打开图片输入面板',async()=>{await h.click('[data-menu="md-insert-menu"]');await h.click('[data-md="image"]');});const chooser=h.page.waitForEvent('filechooser');await h.click('#img-file');await (await chooser).setFiles(path.join(h.materials,'reading-map.png'));await h.expect.poll(()=>h.page.evaluate(()=>imgState.rawW)).toBe(1200);h.evidence.push({assertion:'local_image_loaded',width:1200});});
add('F029',imagePrepare,async h=>{await h.step('旋转和翻转图片',()=>h.click('#img-rot-r'));await h.click('#img-flip-x');await h.step('撤销、重做，再恢复原图',()=>h.click('#img-undo'));await h.click('#img-redo');await h.click('#img-reset');await h.expect.poll(()=>h.page.evaluate(()=>imgState.angle)).toBe(0);h.evidence.push({assertion:'image_history_and_reset'});});
add('F030',imagePrepare,async h=>{await h.step('插入处理后的图片',()=>h.click('#img-insert'));await h.expect.poll(()=>h.page.evaluate(()=>getEditContent())).toContain('![');const content=await h.page.evaluate(()=>getEditContent());const imgs=await h.page.evaluate(()=>state.assets);h.evidence.push({assertion:'image_inserted',assets:!!imgs,markdown:content.slice(-180)});});
const chunks=async h=>{fs.writeFileSync(path.join(h.materials,'论证计算.md'),'# 阅读记录统计\n\n```javascript {cmd=true}\nconsole.log(35 + 28 + 42 + 25);\n```\n\n```javascript {cmd=true}\nconsole.log("平均每次阅读", 130 / 4);\n```\n');await h.open('论证计算.md');};
add('F037',chunks,async h=>{await h.step('运行代码块并检查真实计算结果',()=>h.click('.code-chunk-run-btn'));await h.expect(h.page.locator('.code-chunk-output').first()).toContainText('130');await h.click('.code-chunk-copy-btn');await h.step('清空输出',()=>h.click('.code-chunk-clear-btn'));h.evidence.push({assertion:'javascript_execution_output',value:130});});
add('F038',chunks,async h=>{await h.step('运行文档中的全部代码块',()=>h.more('btn-run-all-chunks'));await h.expect(h.page.locator('.code-chunk-output').nth(0)).toContainText('130');await h.expect(h.page.locator('.code-chunk-output').nth(1)).toContainText('32.5');h.evidence.push({assertion:'both_chunks_executed'});});
add('F039',async h=>{fs.writeFileSync(path.join(h.materials,'论证关系图.md'),'# 论证关系图\n\n```mermaid\nflowchart LR\n A[观察] --> B[前提]\n B --> C[结论]\n D[反例] --> B\n```\n');await h.open('论证关系图.md');},async h=>{await h.step('查看离线渲染的论证关系图',()=>h.page.locator('#content svg').first().scrollIntoViewIfNeeded());await h.expect(h.page.locator('#content svg').first()).toBeVisible();h.evidence.push({assertion:'real_local_mermaid_svg'});});
add('F040',async h=>{fs.writeFileSync(path.join(h.materials,'论证流程.md'),'# 论证流程\n\n```plantuml\n@startuml\nstart\n:记录观察;\n:检查前提;\n:修订结论;\nstop\n@enduml\n```\n');await h.open('论证流程.md');},async h=>{const remote=h.page.waitForResponse(r=>new URL(r.url()).pathname==='/api/diagram/render'&&r.request().postDataJSON()?.allow_remote===true,{timeout:30000});remote.catch(()=>{});await h.step('显式允许这一次 PlantUML 远程渲染',()=>h.click('.diagram-allow-remote-btn'));const d=await(await remote).json();if(!d.ok)throw Error('Remote diagram: '+d.error_code);await h.expect(h.page.locator('#content .diagram-preview svg:not(.tb-ic)').first()).toContainText('检查前提',{timeout:30000});h.evidence.push({assertion:'plantuml_remote_svg_loaded',characters:d.svg.length});});
add('F098',async h=>h.open('论证示例.js'),async h=>{await h.step('复制代码文件内容',()=>h.click('#btn-code-copy'));await h.step('转换为 Markdown 代码文档',()=>h.click('#btn-code-to-md'));await h.expect(h.page.locator('#content')).toContainText('阅读总时长');h.evidence.push({assertion:'code_document_to_markdown'});});

const convertPrepare=async h=>{await h.click('#w-convert');await visible(h,'#convert-modal');};
const pluginPrepare=async h=>{await convertPrepare(h);await h.click('#btn-open-plugins');await h.expect(h.page.locator('.plugin-card').first()).toBeVisible();};
add('F058',convertPrepare,async h=>{await h.step('选择原创 EPUB、PDF、数据与邮件资料',async()=>{const chooser=h.page.waitForEvent('filechooser');await h.click('#convert-files');await (await chooser).setFiles(['哲学阅读工作坊.epub','证据与论证.pdf','研究数据.csv','讨论邀请.eml'].map(x=>path.join(h.materials,x)));});await h.expect.poll(()=>h.page.locator('.batch-item.ok').count(),{timeout:30000}).toBe(4);h.evidence.push({assertion:'four_real_conversions_succeeded'});});
add('F059',convertPrepare,async h=>{const chooser=h.page.waitForEvent('filechooser');await h.step('查看批量转换进度和结果',()=>h.click('#convert-files'));await (await chooser).setFiles(['证据与论证.pdf','研究数据.csv'].map(x=>path.join(h.materials,x)));await h.expect.poll(()=>h.page.locator('.batch-item.ok').count(),{timeout:30000}).toBe(2);await h.step('点击任务行打开生成的 Markdown',()=>h.click('.batch-item.ok'));await h.expect(h.page.locator('#content')).toContainText('证据');h.evidence.push({assertion:'batch_result_opened'});});
add('F060',null,async h=>{const chooser=h.page.waitForEvent('filechooser');await h.step('单文件导入 EPUB，只预览而不覆盖原书',()=>h.click('#w-open'));await (await chooser).setFiles(path.join(h.materials,'哲学阅读工作坊.epub'));await h.expect(h.page.locator('#content')).toContainText('认识与经验');if(fs.existsSync(path.join(h.materials,'哲学阅读工作坊.md')))throw Error('Preview polluted source directory');h.evidence.push({assertion:'epub_preview_without_sibling_md'});});
add('F061',convertPrepare,async h=>{const chooser=h.page.waitForEvent('filechooser');await h.step('导入 ZIP，隔离解包并转换笔记',()=>h.click('#convert-files'));await (await chooser).setFiles(path.join(h.materials,'阅读笔记.zip'));await h.expect.poll(()=>h.page.locator('.batch-item.ok,.batch-item.skipped').count(),{timeout:30000}).toBe(3);h.evidence.push({assertion:'zip_three_entries_converted'});});
add('F062',pluginPrepare,async h=>{
 await h.step('搜索 LaTeX 学术扩展',()=>h.page.locator('#plugin-search').fill('LaTeX'));
 await h.expect(h.page.locator('.plugin-card')).toHaveCount(1);
 await h.expect(h.page.locator('.plugin-card')).toContainText('LaTeX');
 await h.page.locator('#plugin-search').fill('');
 await h.step('按功能分类浏览插件',()=>h.page.locator('#plugin-category-tabs [role="tab"]').nth(2).click());
 await h.step('切换为仅看已安装，再恢复全部插件',async()=>{await h.click('#plugin-installed-filter');await h.expect(h.page.locator('#plugin-installed-filter')).toHaveAttribute('aria-pressed','true');await h.click('#plugin-installed-filter');});
 await h.step('刷新插件状态并查看运行信息',async()=>{await h.click('#plugin-refresh');await h.click('.plugin-runtime-details summary');});
 await h.expect(h.page.locator('#plugin-ffmpeg-badge')).toBeVisible();
 h.evidence.push({assertion:'real_plugin_search_category_installed_filter_refresh_and_runtime',cards:await h.page.locator('.plugin-card').count()});
});
const pluginId='pylatexenc';
const ensurePlugin=async h=>{await h.api('/api/plugins/install',{plugin_id:pluginId});await pluginPrepare(h);};
add('F063',async h=>{await h.api('/api/plugins/uninstall',{plugin_id:pluginId}).catch(()=>{});await pluginPrepare(h);},async h=>{await h.step('安装本地 Rust 学术扩展',()=>h.click(`[data-plugin-id="${pluginId}"] [data-action="install"]`));await h.click('#confirm-action');await h.expect(h.page.locator(`[data-plugin-id="${pluginId}"] [data-action="uninstall"]`)).toBeVisible();const d=await h.api('/api/plugins/list');if(!d.plugins[pluginId].installed)throw Error('Plugin not installed');h.evidence.push({assertion:'native_plugin_manifest_installed'});});
add('F064',ensurePlugin,async h=>{const selector=`[data-plugin-id="${pluginId}"] label.plugin-switch`;await h.step('切换扩展开关并检查持久化状态',()=>h.click(selector));await h.expect.poll(async()=>{const d=await h.api('/api/plugins/list');return d.plugins[pluginId].enabled;}).toBe(false);await h.click(selector);await h.expect.poll(async()=>{const d=await h.api('/api/plugins/list');return d.plugins[pluginId].enabled;}).toBe(true);h.evidence.push({assertion:'plugin_toggle_saved'});});
add('F065',ensurePlugin,async h=>{await h.step('卸载扩展，确认后移除本地配置',()=>h.click(`[data-plugin-id="${pluginId}"] [data-action="uninstall"]`));await h.click('#confirm-action');await h.expect(h.page.locator(`[data-plugin-id="${pluginId}"] [data-action="install"]`)).toBeVisible();const d=await h.api('/api/plugins/list');if(d.plugins[pluginId].installed)throw Error('Plugin still installed');h.evidence.push({assertion:'native_plugin_manifest_removed'});});
add('F066',null,async h=>{const chooser=h.page.waitForEvent('filechooser');await h.step('识别扫描资料中的英文正文',()=>h.click('#w-ocr'));await (await chooser).setFiles(path.join(h.materials,'scan-reading.png'));await h.expect(h.page.locator('#content')).toContainText('Observations',{timeout:30000});h.evidence.push({assertion:'actual_windows_ocr_text'});});
add('F069',read,async h=>{await h.page.evaluate(()=>navigator.clipboard.writeText('# 阅读讨论\n\n请准备一份观察记录和一个反例。'));await h.step('从真实剪贴板新建 Markdown 文档',()=>h.more('btn-clipboard-new'));await h.expect(h.page.locator('#content')).toContainText('请准备一份观察记录');h.evidence.push({assertion:'clipboard_document_created'});});

const exportPrepare=async h=>{await read(h);await h.more('btn-print');await h.expect(h.page.locator('#export-modal')).toBeVisible();};
add('F070',exportPrepare,async h=>{for(const fmt of ['docx','epub','html','tex','presentation','pdf'])await h.step('切换导出格式 '+fmt.toUpperCase(),()=>h.click('#export-tab-'+fmt));await h.expect.poll(()=>h.page.evaluate(()=>state.export.fmt)).toBe('pdf');h.evidence.push({assertion:'six_export_format_tabs'});});
add('F071',exportPrepare,async h=>{await h.step('加载商务预设',()=>h.click('.exp-preset-card[data-preset="business"]'));await h.step('保存当前版式为自定义预设',()=>h.click('#exp-save-preset'));await h.page.locator('#exp-save-input').fill('哲学阅读工作坊版式');await h.click('#exp-save-ok');await h.click('#exp-reset');const d=await h.api('/api/export/presets');if(!JSON.stringify(d).includes('哲学阅读工作坊版式'))throw Error('Preset not persisted');h.evidence.push({assertion:'custom_preset_saved_to_backend'});});
add('F072',exportPrepare,async h=>{await h.expect(h.page.locator('#export-preview-card img')).toBeVisible({timeout:30000});await h.step('打开真实 PDF 页面的大预览',()=>h.click('#export-preview-card'));await visible(h,'#export-preview-modal');await h.click('#export-preview-next-btn');await h.click('#export-preview-prev-btn');await h.click('#export-preview-close');h.evidence.push({assertion:'backend_generated_pdf_preview'});});
add('F074',exportPrepare,async h=>{await h.step('导出 PDF 并选择保存位置',async()=>{const dialog=h.native('dialog',path.join(h.work,'哲学阅读手册.pdf'));await h.click('#export-run');await dialog;});await h.expect(h.page.locator('#export-result')).toHaveClass(/ok/,{timeout:30000});const pdf=fs.readFileSync(path.join(h.work,'哲学阅读手册.pdf'));if(!pdf.subarray(0,5).equals(Buffer.from('%PDF-')))throw Error('Not a genuine PDF');h.evidence.push({assertion:'real_export_pdf_file',bytes:pdf.length});});
add('F076',async h=>h.open('阅读讨论演示.md'),async h=>{await h.step('从 Markdown 开启演讲演示',()=>h.more('btn-presentation-menu'));const f=h.page.frameLocator('.presentation-iframe');await h.expect(f.locator('.reveal')).toBeVisible();await h.step('翻到下一张幻灯片',()=>f.locator('.navigate-right').click());await h.page.keyboard.press('Escape');await h.click('#presentation-close-btn');h.evidence.push({assertion:'actual_reveal_player_navigation'});});
add('F077',read,async h=>{await h.step('开启局域网共享，生成访问二维码',()=>h.more('btn-share'));await h.click('#share-start');await h.expect(h.page.locator('#share-stop')).toBeVisible();const d=await h.api('/api/share/status');if(!d.running)throw Error('Share not actually running');await h.step('关闭共享会话',()=>h.click('#share-stop'));h.evidence.push({assertion:'real_lan_share_started_stopped'});});
add('F078',async h=>h.open('notes/认识与经验.md'),async h=>{await h.step('打开真实笔记关系图',()=>h.more('btn-graph'));await visible(h,'#graph-modal');await h.click('#graph-btn-zoom-in');await h.click('#graph-btn-zoom-out');await h.click('#graph-btn-dimension');await h.click('#graph-btn-fx');await h.click('#graph-btn-reset');h.evidence.push({assertion:'real_index_graph',stats:await h.page.locator('#graph-stats-badge').innerText()});});
add('F079',async h=>{await h.open('notes/认识与经验.md');await h.more('btn-graph');},async h=>{await h.step('筛选关联笔记并查看节点详情',()=>h.page.locator('#graph-search').fill('自由'));await h.click('#graph-node-list button');await h.click('#graph-labels');await h.click('#graph-neighbors');await h.expect(h.page.locator('#graph-detail')).toBeVisible();h.evidence.push({assertion:'graph_filter_and_selection'});});
add('F080',async h=>h.open('notes/认识与经验.md'),async h=>{await h.step('查看真实反向引用',()=>h.more('btn-backlinks-menu'));await visible(h,'#backlinks-panel');await h.step('切换正向链接并筛选目标',()=>h.click('#backlinks-panel [data-tab="outgoing"]'));await h.page.locator('#backlinks-search').fill('自由');await h.click('#backlinks-content button');await h.expect.poll(()=>h.page.evaluate(()=>state.file)).toContain('自由与责任');h.evidence.push({assertion:'bidirectional_link_opened'});});
add('F081',async h=>{fs.writeFileSync(path.join(h.materials,'待修复笔记.md'),'# 研究笔记\n\n```javascript\nconsole.log("观察与解释");\n');await h.open('待修复笔记.md');},async h=>{await h.step('查看显示层修复报告',()=>h.click('#btn-fix'));await visible(h,'#fix-modal');await h.step('另存修复版，保留原稿',()=>h.click('#fix-save'));await h.expect.poll(()=>fs.readdirSync(h.materials).some(f=>f.includes('.readmd'))).toBe(true);h.evidence.push({assertion:'fixed_copy_created_original_retained'});});
add('F083',read,async h=>{await h.step('加载样式定制面板',()=>h.more('btn-style-custom'));await h.expect(h.page.locator('#style-custom-css')).toBeEnabled();await h.step('采用阅读字体预设并保存',()=>h.click('#btn-preset-font'));await h.click('#style-modal-save');const d=await h.api('/api/style');h.evidence.push({assertion:'custom_style_saved',nonempty:JSON.stringify(d).length>10});});
add('F084',read,async h=>{await h.step('搜索并切换界面语言',()=>h.more('btn-lang'));await h.page.locator('#lang-search-input').fill('English');await h.click('#lang-list button');await h.expect(h.page.locator('#btn-open')).toHaveAttribute('title',/Open/i);h.evidence.push({assertion:'locale_changed_to_english'});});
add('F097',edit,async h=>{await h.text('\n暂不保存的研究假设');await h.step('离开编辑时选择取消，保留当前输入',()=>h.click('#edit-cancel'));await visible(h,'#close-confirm-modal');await h.click('#close-confirm-cancel');await h.assertText('暂不保存的研究假设');await h.step('再次离开，放弃修改并保留恢复记录',()=>h.click('#edit-cancel'));await h.click('#close-confirm-discard');const d=await h.api('/api/documents/history');if(!d.entries.some(e=>e.kind==='discarded'))throw Error('Discarded draft not recoverable');h.evidence.push({assertion:'dirty_close_cancel_and_recovery'});});

const aiPrepare=async h=>{await read(h);await h.click('#btn-ai');await h.page.evaluate(async current=>{await loadAiOnDemand();if(current)fillAiProviders(state.ai.providers,current);},h.demoCurrent);await h.expect(h.page.locator('#ai-prompt')).toBeVisible();};
const aiAnswer=async h=>{await aiPrepare(h);await h.page.locator('#ai-template').selectOption({label:'自由提问'}).catch(()=>{});await h.page.locator('#ai-prompt').fill('请只用两句话概括本资料的研究方法，不超过60字。');await h.click('#ai-run');await h.expect.poll(()=>h.page.evaluate(()=>state.ai.raw.length),{timeout:120000}).toBeGreaterThan(10);await h.expect(h.page.locator('#ai-run')).toBeEnabled({timeout:120000});};
const aiSettings=async h=>{await aiPrepare(h);await h.click('#ai-settings-open');await h.expect(h.page.locator('#ai-settings-modal')).toBeVisible();};
add('F041',read,async h=>{await h.step('打开 AI 侧栏',()=>h.click('#btn-ai'));await h.step('展开全屏对话',()=>h.click('#ai-expand-toggle'));await h.click('#ai-expand-toggle');const b=await h.page.locator('#ai-resize-handle').boundingBox();if(b)await h.step('拖动调整对话宽度',async()=>{await h.page.mouse.move(b.x+b.width/2,b.y+90);await h.page.mouse.down();await h.page.mouse.move(b.x-90,b.y+90,{steps:8});await h.page.mouse.up();});await h.click('#ai-close');h.evidence.push({assertion:'ai_panel_expansion_resize_close'});});
add('F042',aiPrepare,async h=>{await h.page.locator('#ai-prompt').fill('请只用两句话概括本资料的研究方法，不超过60字。');await h.step('发送问题，读取当前文档并得到真实模型回复',()=>h.click('#ai-run'));await h.expect.poll(()=>h.page.evaluate(()=>state.ai.raw.length),{timeout:120000}).toBeGreaterThan(10);await h.expect(h.page.locator('#ai-run')).toBeEnabled({timeout:120000});h.evidence.push({assertion:'real_model_answer',characters:await h.page.evaluate(()=>state.ai.raw.length)});});
add('F043',aiAnswer,async h=>{await h.step('复制真实模型回复',()=>h.click('.ai-bubble-act-btn'));const text=await h.page.evaluate(()=>navigator.clipboard.readText());if(text.length<10)throw Error('Empty AI clipboard');const ctx=h.page.locator('.ai-doc-toggle,details.ai-doc-context summary').first();if(await ctx.count())await h.step('展开文档上下文',()=>ctx.click());h.evidence.push({assertion:'real_answer_copied',characters:text.length});});
add('F044',aiAnswer,async h=>{const original=fs.readFileSync(path.join(h.materials,'哲学阅读研究手册.md'),'utf8');await h.step('将 AI 回复应用为未保存副本',()=>h.click('.ai-bubble-actions button:nth-child(2)'));await h.expect.poll(()=>h.page.evaluate(()=>getActiveTab().isVirtual)).toBe(true);if(fs.readFileSync(path.join(h.materials,'哲学阅读研究手册.md'),'utf8')!==original)throw Error('AI changed original');h.evidence.push({assertion:'real_ai_copy_source_untouched'});});
add('F045',async h=>{await h.edit();await h.page.evaluate(async current=>{await loadAiOnDemand();if(current)fillAiProviders(state.ai.providers,current);},h.demoCurrent);await h.text('\n观察记录需要清楚地分开事实和解释。');await h.page.keyboard.press('Home');await h.page.keyboard.press('Shift+End');},async h=>{await h.step('打开文内 AI，润色选中段落',()=>h.page.keyboard.press('Alt+K'));await h.click('.edit-ai-act-chip[data-act="polish"]');await h.expect(h.page.locator('#edit-ai-apply')).toBeEnabled({timeout:120000});await h.step('应用润色结果，再撤销本次修改',()=>h.click('#edit-ai-apply'));await h.page.keyboard.press('Control+Z');await h.assertText('观察记录需要清楚地分开事实和解释。');h.evidence.push({assertion:'real_inline_ai_one_undo'});});
add('F046',aiSettings,async h=>{await h.step('展开高级参数与提供商目录',()=>h.click('.conn-advanced summary'));await h.click('.ai-provider-directory summary');await h.step('搜索官方连接与上游提供商目录',()=>h.page.locator('#ai-provider-search').fill('OpenAI'));await h.expect(h.page.locator('#ai-provider-cards button').first()).toBeVisible();await h.page.locator('#ai-provider-search').fill('');await visible(h,'.ai-provider-directory');h.evidence.push({assertion:'real_provider_catalog_loaded'});});
add('F047',aiSettings,async h=>{await h.step('新建演示连接',()=>h.click('#ai-provider-new'));await h.click('.conn-advanced summary');await h.page.locator('#ai-provider-name').fill('阅读小组演示连接');await h.page.locator('#ai-base-url').fill('https://api.example.test/v1');await h.step('删除刚创建的演示连接',async()=>{h.page.once('dialog',d=>d.accept());await h.click('#ai-provider-delete');});await h.expect.poll(()=>h.page.evaluate(()=>state.ai.providers.some(p=>p.name==='阅读小组演示连接'))).toBe(false);h.evidence.push({assertion:'custom_provider_created_deleted'});});
add('F048',async h=>{await aiSettings(h);await h.click('#ai-provider-new');},async h=>{await h.step('输入演示占位密钥，默认隐藏',()=>h.page.locator('#ai-key').fill('demo-placeholder-not-a-real-key'));await h.expect(h.page.locator('#ai-key')).toHaveAttribute('type','password');await h.step('显示刚输入的占位内容，再清空',()=>h.click('#ai-key-toggle'));await h.click('#ai-key-clear');await h.expect(h.page.locator('#ai-key')).toHaveValue('');h.evidence.push({assertion:'placeholder_key_visibility_clear_only_no_user_key'});});
add('F049',aiSettings,async h=>{await h.step('展开高级参数，检查所有配置可达',()=>h.click('.conn-advanced summary'));await h.page.locator('#ai-stream').uncheck();await h.step('保存连接参数',()=>h.click('#ai-save-key'));const cfg=await h.api('/api/ai/config');if(!cfg.current?.provider_id)throw Error('Selection not saved');h.evidence.push({assertion:'real_ai_connection_saved'});});
add('F050',aiSettings,async h=>{await h.step('测试现有连接，等待明确反馈',()=>h.click('#ai-test-connection'));await h.expect(h.page.locator('#ai-test-connection')).toBeEnabled({timeout:60000});await h.expect(h.page.locator('#ai-conn-status')).toContainText(/连接正常|可用|成功/,{timeout:60000});h.evidence.push({assertion:'real_connection_model_api_succeeded'});});
add('F051',aiAnswer,async h=>{await h.step('打开自动保存的真实会话历史',()=>h.click('#ai-history-open'));await visible(h,'#ai-history-modal');await h.expect(h.page.locator('.ai-history-load').first()).toBeVisible();await h.step('导出当前会话 Markdown',async()=>{const download=h.page.waitForEvent('download');await h.click('#ai-history-export');const d=await download;await d.saveAs(path.join(h.work,'conversation.md'));});if(fs.readFileSync(path.join(h.work,'conversation.md'),'utf8').length<50)throw Error('Conversation export empty');h.evidence.push({assertion:'real_session_saved_exported'});});
const skillPrepare=async h=>{await aiPrepare(h);await h.click('#ai-tpl-btn');await h.expect(h.page.locator('#tpl-modal')).toBeVisible();};
add('F052',skillPrepare,async h=>{await h.step('搜索并浏览内置阅读 Skill',()=>h.page.locator('#tpl-search').fill('总结'));await h.click('#tpl-list li[role="option"]');await visible(h,'#tpl-skill-overview');h.evidence.push({assertion:'skill_overview_loaded'});});
const newSkill=async h=>{await h.click('#tpl-new');await h.page.locator('#tpl-name').fill('哲学论证分析');await h.page.locator('#tpl-system').fill('请区分观察、前提和结论，保留原文的不确定性。');await h.page.locator('#tpl-user').fill('请分析以下论证：\n{doc}\n\n{prompt}');await h.click('#tpl-save');await h.expect.poll(()=>h.page.evaluate(()=>state.ai.templates.some(t=>t.name==='哲学论证分析'))).toBe(true);};
add('F053',skillPrepare,async h=>{await h.step('新建并保存原创论证分析 Skill',()=>newSkill(h));await h.step('复制为另一个可编辑模板',()=>h.click('#tpl-copy'));await h.page.locator('#tpl-name').fill('哲学论证分析修订');await h.click('#tpl-save');await h.step('删除修订副本',()=>h.click('#tpl-del'));if(await h.page.locator('#confirm-action').isVisible())await h.click('#confirm-action');h.evidence.push({assertion:'skill_create_save_copy_delete'});});
add('F054',skillPrepare,async h=>{await h.step('填写用途，请 AI 生成 Skill 草稿',()=>h.click('#tpl-ai-generate'));await h.page.locator('#skill-create-name').fill('哲学读书会纪要');await h.page.locator('#skill-create-purpose').fill('用简短 Markdown 整理问题、论证与待核查事项。');await h.click('#skill-create-go');await h.wait(()=>h.expect(h.page.locator('#tpl-editor-fields')).toBeVisible({timeout:120000}));await h.expect(h.page.locator('#tpl-system')).not.toHaveValue('');h.evidence.push({assertion:'real_ai_skill_draft_generated'});});
add('F055',async h=>{await skillPrepare(h);await newSkill(h);await h.click('#tpl-edit');},async h=>{await h.step('评估并发布原创 Skill',()=>h.click('#tpl-publish'));await h.click('#confirm-action');await h.delay(600);await h.step('停用再启用 Skill',()=>h.click('#tpl-toggle'));await h.click('#tpl-toggle');const download=h.page.waitForEvent('download');await h.step('导出单个 Skill',()=>h.click('#tpl-export-one'));await (await download).saveAs(path.join(h.work,'skill.md'));h.evidence.push({assertion:'skill_published_enabled_exported',bytes:fs.statSync(path.join(h.work,'skill.md')).size});});
add('F056',skillPrepare,async h=>{const input=path.join(h.materials,'演示Skill.json');fs.writeFileSync(input,JSON.stringify({templates:[{id:'demo-original-reasoning',name:'原创研究辅助',system:'请检查前提。',user:'{doc}',action:'custom'}]}));await h.step('导入原创 JSON 模板',()=>h.page.locator('#tpl-file-input').setInputFiles(input));await h.expect.poll(()=>h.page.evaluate(()=>state.ai.templates.some(t=>t.id==='demo-original-reasoning'))).toBe(true);const download=h.page.waitForEvent('download');await h.step('导出全部模板',()=>h.click('#tpl-export-btn'));await (await download).saveAs(path.join(h.work,'skills.json'));h.evidence.push({assertion:'json_skill_import_and_full_export'});});
add('F073',async h=>{await exportPrepare(h);await h.page.evaluate(async current=>{await loadAiOnDemand();if(current)fillAiProviders(state.ai.providers,current);},h.demoCurrent);},async h=>{await h.reveal('#exp-ai-prompt');await h.page.locator('#exp-ai-prompt').fill('使用A4页面，正文12pt，墨绿色标题，留白适中。');await h.step('AI 生成版式并应用到预览',()=>h.click('#exp-ai-gen-btn'));await h.wait(()=>h.expect(h.page.locator('#exp-ai-gen-btn')).toBeEnabled({timeout:180000}));await h.expect(h.page.locator('#exp-preset')).toHaveValue('__custom__');h.evidence.push({assertion:'real_ai_export_style_generated'});});
add('F082',async h=>{await read(h);await h.page.evaluate(async current=>{await loadAiOnDemand();if(current)fillAiProviders(state.ai.providers,current);},h.demoCurrent);await h.more('btn-fix');},async h=>{const original=fs.readFileSync(path.join(h.materials,'哲学阅读研究手册.md'),'utf8');await h.step('AI 深度排版生成安全副本',()=>h.click('#fix-ai-btn'));await h.wait(()=>h.expect.poll(()=>h.page.evaluate(()=>state.tabs.some(t=>t.source==='ai')),{timeout:120000}).toBe(true));if(fs.readFileSync(path.join(h.materials,'哲学阅读研究手册.md'),'utf8')!==original)throw Error('AI repair changed original');h.evidence.push({assertion:'real_ai_repair_safe_copy'});});

const petPrepare=async h=>{await read(h);await h.more('btn-pet');await h.expect(h.page.locator('#pet-settings-modal')).toBeVisible();await h.expect(h.page.locator('.pet-character-card').first()).toBeVisible();};
add('F086',petPrepare,async h=>{await h.step('查看完整角色预览和三组设置',()=>h.click('[data-pet-section="companion"]'));await h.click('[data-pet-section="settings"]');await h.click('[data-pet-section="characters"]');await visible(h,'#pet-preview-character');h.evidence.push({assertion:'pet_workbench_three_tabs'});});
add('F087',petPrepare,async h=>{await h.step('搜索角色并单独收藏',()=>h.page.locator('#pet-roster-search').fill('mochi'));await h.click('.pet-fav-btn');await h.step('选择原有精灵角色',()=>h.click('.pet-character-card[data-slug="mochi"]'));const d=await h.api('/api/pets');if(d.active!=='mochi')throw Error('Selected sprite not persisted');h.evidence.push({assertion:'sprite_character_selected_and_favorited'});});
add('F088',petPrepare,async h=>{const sprite=path.join(h.materials,'原创演示角色.png');fs.copyFileSync(path.join(h.root,'assets/pet/hermes-sprite.png'),sprite);await h.step('导入演示精灵图副本',()=>h.page.locator('#pet-gallery-import').setInputFiles(sprite));await h.page.locator('#pet-roster-search').fill('原创演示角色');await h.click('.pet-character-card');await h.expect(h.page.locator('#pet-gallery-delete')).toBeVisible();await h.step('删除刚导入的自定义副本',()=>h.click('#pet-gallery-delete'));if(await h.page.locator('#confirm-action').isVisible())await h.click('#confirm-action');const d=await h.api('/api/pets');h.evidence.push({assertion:'custom_sprite_imported_removed',remaining:d.pets?.length});});
add('F089',petPrepare,async h=>{await h.click('[data-pet-section="settings"]');await h.step('启用伴读角色并缩小尺寸',()=>h.click('label.plugin-switch:has(#pet-enabled)'));await h.page.locator('#pet-scale').fill('16');await h.page.locator('#pet-scale').dispatchEvent('input');await h.page.locator('#pet-scale').dispatchEvent('change');await h.step('关闭置顶并保存窗口行为',()=>h.click('label.plugin-switch:has(#pet-topmost)'));await h.expect.poll(async()=>{const d=await h.api('/api/pets/status');return(d.status||d).preferences.scale;}).toBe(.16);h.evidence.push({assertion:'pet_small_scale_persisted'});});
add('F090',petPrepare,async h=>{await h.click('[data-pet-section="settings"]');await h.page.locator('#pet-runtime').selectOption('desktop');await h.step('从本地随包资源安装桌宠扩展',()=>h.click('#pet-install-runtime'));await h.expect.poll(async()=>{const d=await h.api('/api/pets/status');return(d.status||d).adapter?.available;},{timeout:60000}).toBe(true);h.evidence.push({assertion:'local_native_pet_runtime_available'});});
add('F091',petPrepare,async h=>{await h.click('[data-pet-section="companion"]');await h.step('选择安静陪伴并打招呼',()=>h.click('#pet-mode-quiet'));await h.click('#pet-say-hello');await h.step('摸摸头、喂食与休息唤醒',()=>h.click('[data-pet-action="pet"]'));await h.click('[data-pet-action="feed"]');await h.click('[data-pet-action="rest"]');await h.click('[data-pet-action="wake"]');await h.expect(h.page.locator('#pet-life-stats')).not.toHaveText('');h.evidence.push({assertion:'persistent_companion_interactions',stats:await h.page.locator('#pet-life-stats').innerText()});});
add('F092',async h=>{await read(h);await h.api('/api/pets/configure',{enabled:true,in_app:true,renderer:'hermes-sprite',character:'',scale:.22,lock_position:false});await h.page.evaluate(async()=>syncPetWidgetVisibility(await fetchPetRuntimeStatus()));await h.expect(h.page.locator('#pet-character-wrap')).toBeVisible();},async h=>{await h.step('点击原有精灵角色，播放互动与台词',()=>h.click('#pet-character-wrap'));const b=await h.page.locator('#pet-character-wrap').boundingBox();await h.step('拖动角色到新的阅读位置',async()=>{await h.page.mouse.move(b.x+b.width/2,b.y+b.height/2);await h.page.mouse.down();await h.page.mouse.move(b.x-180,b.y-90,{steps:10});await h.page.mouse.up();});await visible(h,'#pet-bubble');h.evidence.push({assertion:'in_app_pet_click_drag',position:await h.page.locator('#pet-character-wrap').boundingBox()});});
add('F085',read,async h=>{await h.step('向真实更新服务检查版本',()=>h.more('btn-check-update'));await h.delay(2000);const res=await h.api('/api/update/check');h.evidence.push({assertion:'real_update_service_checked',has_update:!!res.has_update,current_version:res.current_version,latest_version:res.latest_version});});
add('F057',skillPrepare,async h=>{await h.step('从 ZIP 预览原创 Skill 包',()=>h.click('#tpl-import-btn'));const chooser=h.page.waitForEvent('filechooser');await h.click('#tpl-import-source-zip');await (await chooser).setFiles(path.join(h.materials,'原创研究Skill.zip'));await h.expect(h.page.locator('#tpl-github-apply-btn')).toBeEnabled({timeout:30000});await h.step('选择有效 Skill 并确认导入',()=>h.click('#tpl-github-apply-btn'));await h.click('#confirm-action');await h.expect.poll(()=>h.page.evaluate(()=>state.ai.templates.some(t=>t.name?.includes('philosophy')||t.id?.includes('philosophy')))).toBe(true);h.evidence.push({assertion:'real_zip_skill_preview_apply'});});
add('F100',convertPrepare,async h=>{await h.step('选择英语识别模型，转写原创讨论录音',()=>h.page.locator('#convert-speech-language').selectOption('en'));const chooser=h.page.waitForEvent('filechooser');await h.click('#convert-files');await (await chooser).setFiles(path.join(h.materials,'reading-discussion.wav'));await h.expect(h.page.locator('.batch-item.ok')).toBeVisible({timeout:30000});await h.click('.batch-item.ok');await h.expect(h.page.locator('#content')).toContainText(/observations|inquiry|argument/i);h.evidence.push({assertion:'real_sapi_english_transcription'});});
add('F067',read,async h=>{await h.step('填写网页网址，调整页数并选择图片策略',()=>h.more('btn-web'));await h.page.locator('#url-input').fill('https://example.org');await h.click('#url-pages-inc');await h.click('#url-pages-dec');await h.page.locator('#url-images').uncheck();await h.expect(h.page.locator('#url-pages')).toHaveValue('1');h.evidence.push({assertion:'web_form_pages_image_options'});});
// Native-only recipes are dispatched by record.mjs --native; all host bridges remain real.
recipes.F002={native:true,prepare:read,run:async h=>{const chooser=h.native('dialog',h.materials,true);await h.step('从当前文档目录选择原创资料文件夹',()=>h.click('#btn-folder'));await chooser;await h.expect.poll(()=>h.page.evaluate(()=>state.folder&&state.folder.replaceAll('\\','/'))).toBe(h.materials.replaceAll('\\','/'));await h.click('#file-list .tree-row:has-text("哲学阅读研究手册")');await h.expect(h.page.locator('#content')).toContainText('论证与反例');h.evidence.push({assertion:'real_native_folder_tree'});}};
recipes.F104={native:true,prepare:edit,run:async h=>{await h.text('\n退出前暂存的阅读结论');await h.step('从顶栏退出应用，先取消关闭',()=>h.more('btn-app-exit'));await visible(h,'#close-confirm-modal');await h.click('#close-confirm-cancel');await h.assertText('退出前暂存的阅读结论');await h.step('查看已经保留的恢复草稿',()=>h.more('btn-document-history'));await visible(h,'#document-history-modal');h.evidence.push({assertion:'real_native_explicit_quit_cancel_and_recovery'});}};
recipes.F049.captureUi.posterAt=3;
recipes.F104.captureUi={posterAt:2.5};

// Read-only probe assertions and the actual source contract settle selectors.
recipes.F027.run=async h=>{await h.step('切换左右对照预览',()=>h.click('#pv-trigger'));await h.click('[data-pv="right"]');await visible(h,'#preview-pane');const r=await h.page.locator('#pv-splitter').boundingBox();await h.step('拖动分栏调整比例',async()=>{await h.page.mouse.move(r.x+r.width/2,r.y+80);await h.page.mouse.down();await h.page.mouse.move(r.x-100,r.y+80,{steps:10});await h.page.mouse.up();});h.evidence.push({assertion:'split_preview_resize'});};
recipes.F034.run=async h=>{await h.step('插入研究数据统计图',()=>h.insertMenu('btn-insert-diagram'));await h.page.locator('#diagram-type').selectOption('vega-lite');await h.page.locator('#diagram-code').fill(JSON.stringify({data:{values:[{主题:'认识与经验',分钟:35},{主题:'自由与责任',分钟:28}]},mark:'bar',encoding:{x:{field:'主题',type:'nominal'},y:{field:'分钟',type:'quantitative'}}}));await h.click('#diagram-insert');await h.assertText('vega-lite');};
recipes.F020.run=async h=>{await h.step('查看正文书目引用与悬浮信息',async()=>{const c=h.page.locator('.bib-cite-badge').first();await c.scrollIntoViewIfNeeded();await c.hover();});await visible(h,'.bib-hover-card');h.evidence.push({assertion:'bibliography_hover_card'});};
recipes.F083.run=async h=>{await h.step('加载样式定制面板',()=>h.more('btn-style-custom'));await h.expect(h.page.locator('#style-custom-css')).toBeEnabled();await h.step('应用字体预设并保存',()=>h.click('#btn-preset-font'));await h.click('#style-modal-save');const d=await h.api('/api/style/get');if(!d.data?.css)throw Error('Style not persisted');h.evidence.push({assertion:'custom_css_saved'});};
recipes.F084.prepare=async h=>{await read(h);h.startupBackup=path.join(h.work,'autostart.json');await h.native('autostart-save',h.startupBackup);};
recipes.F084.run=async h=>{try{await h.step('搜索并切换界面语言',()=>h.more('btn-lang'));await h.page.locator('#lang-search-input').fill('English');await h.click('#lang-grid button');await h.expect(h.page.locator('#btn-open')).toHaveAttribute('title',/Open/i);await h.step('查看默认关联的桌面版说明',()=>h.more('btn-assoc'));await h.expect(h.page.locator('#toast')).toHaveText(/.+/);const before=(await h.api('/api/autostart/get')).enabled;await h.step('切换真实开机自启设置',()=>h.more('btn-autostart'));await h.expect.poll(async()=> (await h.api('/api/autostart/get')).enabled).toBe(!before);await h.step('恢复原先的开机自启状态',()=>h.native('autostart-restore',h.startupBackup));if((await h.api('/api/autostart/get')).enabled!==before)throw Error('Startup state did not restore');h.evidence.push({assertion:'locale_browser_association_notice_and_real_autostart_roundtrip',original_startup_restored:true});}finally{await h.native('autostart-restore',h.startupBackup);}};
recipes.F081.run=async h=>{await h.step('查看显示层修复报告',()=>h.more('btn-fix'));await visible(h,'#fix-modal');await h.step('另存修复版，保留原稿',()=>h.click('#fix-save'));await h.expect.poll(()=>fs.readdirSync(h.materials).some(f=>f.includes('.readmd'))).toBe(true);h.evidence.push({assertion:'fixed_copy_created_original_retained'});};
recipes.F011.native=true;
recipes.F098.prepare=async h=>{await h.open('论证示例.js');};
recipes.F098.run=async h=>{await h.step('复制源码并进入源码编辑',()=>h.click('#btn-code-copy'));const c=await h.page.evaluate(()=>navigator.clipboard.readText());if(!c.includes('阅读总时长'))throw Error('Code clipboard empty');await h.click('#btn-code-edit');await h.assertText('阅读总时长');h.evidence.push({assertion:'code_file_copy_edit',ai_actions_require_connection:true});};

recipes.F081.native=true;
recipes.F043.prepare=async h=>{await aiPrepare(h);await h.page.locator('#ai-prompt').fill('给出一个 JavaScript 一行示例，计算 35 + 28，并在代码块后用一句话说明。');await h.click('#ai-run');await h.expect(h.page.locator('#ai-run')).toBeEnabled({timeout:120000});await h.expect(h.page.locator('.ai-code-copy').first()).toBeVisible();};
recipes.F043.run=async h=>{await h.step('复制模型回复和其中的代码块',()=>h.click('.ai-bubble-act-btn'));await h.click('.ai-code-copy');if((await h.page.evaluate(()=>navigator.clipboard.readText())).length<3)throw Error('Code copy was empty');const context=h.page.locator('.ai-user-card-toggle').first();if(await context.count())await h.step('展开再收起文档上下文',async()=>{await context.click();await h.delay(400);await context.click();});await h.step('重新生成这条真实模型回复',()=>h.click('.ai-regen-btn'));await h.wait(()=>h.expect(h.page.locator('#ai-run')).toBeEnabled({timeout:120000}));if((await h.page.evaluate(()=>state.ai.raw)).length<10)throw Error('Regeneration returned no answer');h.evidence.push({assertion:'actual_answer_and_code_copy_context_toggle_and_regeneration'});};
recipes.F051.run=async h=>{await h.step('打开自动保存的会话，修改名称',()=>h.click('#ai-history-open'));await visible(h,'#ai-history-modal');await h.expect(h.page.locator('.ai-history-item').first()).toBeVisible();h.page.once('dialog',d=>d.accept('原创哲学讨论'));await h.page.locator('.ai-history-item').first().locator('button').nth(1).click();await h.expect(h.page.locator('#ai-history-list')).toContainText('原创哲学讨论');await h.step('搜索并重新打开已保存的会话',()=>h.page.locator('#ai-history-search').fill('原创哲学讨论'));await h.click('.ai-history-load');await h.click('#ai-history-open');await h.step('复制回答并导出会话 Markdown',async()=>{await h.click('#ai-history-copy');const download=h.page.waitForEvent('download');await h.click('#ai-history-export');await(await download).saveAs(path.join(h.work,'conversation.md'));});if(fs.readFileSync(path.join(h.work,'conversation.md'),'utf8').length<50)throw Error('Conversation export empty');await h.step('删除刚才的演示会话',async()=>{h.page.once('dialog',d=>d.accept());await h.page.locator('.ai-history-item').filter({hasText:'原创哲学讨论'}).locator('button').last().click();});await h.expect(h.page.locator('#ai-history-list')).not.toContainText('原创哲学讨论');h.evidence.push({assertion:'real_history_rename_search_reload_copy_export_and_delete'});};
recipes.F083.prepare=async h=>{await read(h);await h.page.evaluate(async current=>{await loadAiOnDemand();if(current)fillAiProviders(state.ai.providers,current);},h.demoCurrent);};
recipes.F083.run=async h=>{await h.step('查看阅读字体与表格预设',()=>h.more('btn-style-custom'));await h.expect(h.page.locator('#style-custom-css')).toBeEnabled();await h.click('#btn-preset-font');await h.click('#btn-preset-table');const preset=await h.page.locator('#style-custom-css').inputValue();await h.page.locator('#style-ai-prompt').fill('只生成简短CSS：正文22px，标题墨绿色。head为空字符串。');await h.step('请 AI 生成阅读样式',()=>h.click('#style-ai-gen-btn'));await h.wait(()=>h.expect(h.page.locator('#style-ai-gen-btn')).toBeEnabled({timeout:120000}));const generated=await h.page.locator('#style-custom-css').inputValue();if(generated===preset||generated.length<20)throw Error('AI did not produce a new style');await h.step('保存样式并回到正文查看效果',()=>h.click('#style-modal-save'));const d=await h.api('/api/style/get');if(d.data?.css!==generated)throw Error('Generated style not saved');h.evidence.push({assertion:'actual_font_table_presets_real_ai_css_and_durable_save'});};
recipes.F098.prepare=async h=>{await h.open('论证示例.js');await h.page.evaluate(async current=>{await loadAiOnDemand();if(current)fillAiProviders(state.ai.providers,current);},h.demoCurrent);};
recipes.F098.run=async h=>{await h.step('复制代码并打开源码编辑器',()=>h.click('#btn-code-copy'));if(!(await h.page.evaluate(()=>navigator.clipboard.readText())).includes('阅读总时长'))throw Error('Code clipboard empty');await h.click('#btn-code-edit');await h.assertText('阅读总时长');await h.click('#edit-cancel');await h.step('从代码文件打开 AI 深度解析',()=>h.click('#btn-code-ai-explain'));await h.wait(()=>h.expect(h.page.locator('#ai-run')).toBeEnabled({timeout:120000}));if((await h.page.evaluate(()=>state.ai.raw)).length<10)throw Error('AI analysis was empty');await h.click('#ai-close');await h.step('将代码整理成结构化 Markdown 草稿',()=>h.click('#btn-code-to-md'));await h.wait(()=>h.expect(h.page.locator('#ai-run')).toBeEnabled({timeout:120000}));await h.click('.ai-bubble-actions button:nth-child(2)');await h.expect.poll(()=>h.page.evaluate(()=>getActiveTab().isVirtual)).toBe(true);h.evidence.push({assertion:'all_four_code_header_actions_real_ai_analysis_and_copy'});};
recipes.F074.native=true;
recipes.F058={native:true,prepare:async h=>{
 const dir=path.join(h.materials,'conversion-demo');fs.mkdirSync(dir);
 for(const n of ['研究数据.csv','讨论邀请.eml'])fs.copyFileSync(path.join(h.materials,n),path.join(dir,n));
 fs.writeFileSync(path.join(dir,'研究数据.md'),'# 原有阅读统计\n\n这份输出需要先保留。\n');
 fs.writeFileSync(path.join(dir,'目录入口.md'),'# 转换工作坊\n\n比较文件导入、目录收集与覆盖策略。\n');
 h.convertDemoDir=dir;await h.open('conversion-demo/目录入口.md');await h.more('btn-convert');
},run:async h=>{
 await h.step('选择演示资料文件夹，已有 Markdown 自动跳过',async()=>{const chosen=h.native('dialog',h.convertDemoDir,true);await h.click('#convert-folder');await chosen;});
 await h.expect.poll(()=>h.page.locator('.batch-item.ok,.batch-item.skipped').count(),{timeout:30000}).toBe(2);
 const target=path.join(h.convertDemoDir,'研究数据.md');if(!fs.readFileSync(target,'utf8').includes('这份输出需要先保留'))throw Error('Default batch replaced existing Markdown');
 await h.step('明确勾选覆盖，重新转换并保留旧版本',()=>h.page.locator('#convert-overwrite').check());
 const chosen=h.native('dialog',h.convertDemoDir,true);await h.click('#convert-folder');await chosen;
 await h.expect.poll(()=>h.page.locator('.batch-item.ok').count(),{timeout:30000}).toBe(2);
 if(!fs.readFileSync(target,'utf8').includes('认识与经验'))throw Error('Explicit overwrite did not save converted data');
 const history=await h.api('/api/documents/history');if(!history.entries.some(e=>e.kind==='version'))throw Error('Overwrite did not retain a version');
 h.evidence.push({assertion:'native_folder_real_csv_eml_default_skip_explicit_overwrite_and_history'});
}};
recipes.F075={native:true,prepare:exportPrepare,run:async h=>{await h.reveal('#export-print');await h.page.evaluate(()=>{window.addEventListener('beforeprint',()=>console.info('showcase-system-print-open'),{once:true});window.addEventListener('afterprint',()=>window.showcasePrintClosed=true,{once:true});});await h.step('打开系统打印预览，查看当前正文后取消',async()=>{const opened=h.page.waitForEvent('console',{predicate:m=>m.text()==='showcase-system-print-open'});const clicking=h.click('#export-print');clicking.catch(()=>{});await opened;await h.delay(1700);await h.native('print-cancel');await clicking;});await h.expect.poll(()=>h.page.evaluate(()=>!!window.showcasePrintClosed)).toBe(true);h.evidence.push({assertion:'actual_browser_beforeprint_native_escape_afterprint'});}};
const webPrepare=async h=>{await read(h);await h.more('btn-web');};
recipes.F068={native:true,prepare:webPrepare,run:async h=>{
 const fixture=await webFixture(h.materials);
 try{
  await h.page.locator('#url-private').uncheck();await h.page.locator('#url-input').fill(fixture.url+'/article');
  await h.step('智能提取原创网页正文',()=>h.click('#url-go'));
  await h.expect.poll(()=>h.page.evaluate(()=>webRun.running)).toBe(false);await h.expect(h.page.locator('#content')).toContainText('证据与论证');
  await h.page.locator('#url-input').fill(fixture.url+'/dynamic');await h.page.locator('#url-private').check();const before=new Set(h.debugPorts());
  await h.step('用真实系统 WebView 提取动态内容',()=>h.click('#url-render'));
  await h.expect.poll(()=>h.debugPorts().find(p=>!before.has(p)),{timeout:30000}).toBeTruthy();
  const auxBrowser=await h.chromium.connectOverCDP('http://127.0.0.1:'+h.debugPorts().find(p=>!before.has(p)));
  try{const aux=auxBrowser.contexts().flatMap(c=>c.pages()).find(p=>p.url().startsWith(fixture.url));await h.native('resize-aux');h.capturePage=aux;await aux.locator('#demo-story').filter({hasText:'动态阅读记录'}).waitFor();await h.delay(600);await aux.locator('#readmd-capture-bar button').click();}finally{h.capturePage=null;await auxBrowser.close().catch(()=>{});}
  await h.expect.poll(()=>h.page.evaluate(()=>webRun.running),{timeout:30000}).toBe(false);
  await h.expect(h.page.locator('#content')).toContainText('动态阅读记录',{timeout:30000});
  h.evidence.push({assertion:'real_static_and_system_webview_extraction'});
 }finally{await fixture.close();}
}};
recipes.F101={native:true,prepare:webPrepare,run:async h=>{
 const fixture=await webFixture(h.materials);let auxBrowser;
 try{
  await h.page.locator('#url-private').check();await h.page.locator('#url-input').fill(fixture.url+'/dynamic');const before=new Set(h.debugPorts());
  await h.step('打开隔离网页窗口，进入原创演示会话',()=>h.click('#url-go'));
  await h.expect.poll(()=>h.debugPorts().find(p=>!before.has(p)),{timeout:30000}).toBeTruthy();
  const port=h.debugPorts().find(p=>!before.has(p));auxBrowser=await h.chromium.connectOverCDP('http://127.0.0.1:'+port);
  const aux=auxBrowser.contexts().flatMap(c=>c.pages()).find(p=>p.url().startsWith(fixture.url));if(!aux)throw Error('Own authorization page missing');
  await h.native('resize-aux');h.capturePage=aux;await aux.locator('#demo-login').click();await h.delay(550);
  if(await aux.evaluate(()=>typeof window.pywebview)!=='undefined')throw Error('External page exposed reader bridge');
  await h.step('明确授权本次提取，返回真实正文',()=>aux.locator('#readmd-capture-bar button').click());
  await h.expect.poll(()=>h.page.evaluate(()=>webRun.running),{timeout:30000}).toBe(false);
  await h.expect(h.page.locator('#content')).toContainText('已进入演示会话',{timeout:30000});await h.expect.poll(()=>h.page.evaluate(()=>webRun.privateGrant)).toBe('');
  h.evidence.push({assertion:'real_private_grant_cookies_capture_and_revocation'});
 }finally{h.capturePage=null;await auxBrowser?.close().catch(()=>{});await fixture.close();}
}};


